### ISSUE TITLE
Cannot find this add-on in the statamic marketplace

### ISSUE THREAD

**Issue by de-raaf-media** [reachweb/statamic-resrv#75]
Can you maybe add a link to the readme?

**Comment by afonic** [comment]
Hello! We are currently working on this, we hope to have it in the marketplace by the end of March!

**Comment by de-raaf-media** [comment]
Hey @afonic, any progress? Eager to test it out :-)

**Comment by afonic** [comment]
Hey @de-raaf-media we finished the Livewire components for the frontend. (you can already seem them in dev-main).

Right now I am finishing some lose ends here and there and a colleague is finishing up the docs. We hope to be live within 10 days!

**Comment by de-raaf-media** [comment]
Understood! Just curious to see if this is still being released :-)

**Comment by afonic** [comment]
Hello, I am currently finalising the documentation as there quite a few parts missing and my colleague is creating a starter kit to make it easier to install and try out. We plan to release this to the marketplace in around 10 days.

It will be an one time purchase as are all Statamic add-ons, probably in the $200 range. Feel free to install and try it out until then!

**Comment by afonic** [comment]
Closing this as Resrv is now in the Statamic Marketplace:
https://statamic.com/addons/reach/resrv

**Comment by de-raaf-media** [comment]
Wow! Congrats!
