### ISSUE TITLE
Feature request - add Mollie as a payment provider

### ISSUE THREAD

**Issue by de-raaf-media** [reachweb/statamic-resrv#96]
Would be a nice option.

**Comment by afonic** [comment]
Looks straightforward enough, I will add it to the list!

**Comment by de-raaf-media** [comment]
Thanks @afonic!

**Comment by afonic** [comment]
Better late than never!

This is now implemented as an extra package. Details here: https://resrv.eu/mollie.html

**Comment by de-raaf-media** [comment]
Wow! Very nice! Thanks 👍
